export const ADD_MARKERS="ADD_MARKERS";
export const ADD_MARKERS_SUCCESS="ADD_MARKERS_SUCCESS";
export const ADD_MARKERS_FAILURE="ADD_MARKERS_FAILURE";

export const GET_MARKERS="GET_MARKERS";
export const GET_MARKERS_SUCCESS="GET_MARKERS_SUCCESS";
export const GET_MARKERS_FAILURE="GET_MARKERS_FAILURE";