export const LOGIN_USER="LOGIN_USER";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";

export const CHECK_AUTHENTICATION="CHECK_AUTHENTICATION";
export const CHECK_AUTHENTICATION_AUTHENTICATED="CHECK_AUTHENTICATION_AUTHENTICATED";
export const CHECK_AUTHENTICATION_NOT_AUTHENTICATED="CHECK_AUTHENTICATION_NOT_AUTHENTICATED";

export const CREATE_USER="CREATE_USER";
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE="CREATE_USER_FAILURE";